### ISSUE TITLE
Small hello and some questions

### ISSUE THREAD

**Issue by donaldpipowitch** [utkarshkukreti/munch.rs#1]
Hi @utkarshkukreti, 

sorry for opening an issue here just to say _Hello!_ and ask some questions. I hope that's okay, because there is no `README.md` in this project.

0. Is this project an alternative to [`nom.rs`](https://github.com/Geal/nom)? If so, what are your goals? Be faster, better API, something else...?
0. I'm fairly new to parsing. Does this lib solves the `tokenizer` _and_ `parser` step of a compiler? If so, can I store meta data of a node with this lib? E.g. your nodes (here: [`Value`](https://github.com/utkarshkukreti/munch.rs/blob/master/examples/clojure.rs#L17)) is an `enum` with _unnamed data_ (e.g. `Integer(i64)`). Would be possible to have named data to store things like line and column or if I'd parse HTML to store things like _Is this a self closing tag?_ for every node?

Thank you.

(FYI: I try to convert the super tiny compiler [to Rust](https://github.com/donaldpipowitch/the-super-tiny-compiler-in-rust/) and would like to know how I can apply your lib to this.)

**Comment by utkarshkukreti** [comment]
Hello!

Yes, it is an alternative to nom. My goal is to have a better API and be as fast as possible. While in some benchmarks I'm seeing munch is faster than nom, I would expect nom to catch up in those benchmarks pretty easily. So, vs nom, the primary goal is to have a better API.

Yes, this is meant to replace both the tokenizer/lexer and parser stages of a compiler, like almost all parser combinator libraries I can think of.

Yes, you can store such metadata. ([There is a parser to get the byte position](https://github.com/utkarshkukreti/munch.rs/blob/09a5c6a415471a8fbfd079438ead51bb1b7fa6a5/tests/lib.rs#L511-L532) but for performance reasons, the parser doesn't keep track of the line/column position.) Here's a simple example of parsing a word with an optional exclamation, and returning both the word as a `&str` and exclamation as a `bool`:

```rust
extern crate munch;

use munch::{Optional, Parser};
use munch::str::TakeWhile1;

#[derive(Debug)]
pub struct Value<'a> {
    word: &'a str,
    exclamation: bool,
}

pub fn main() {
    let mut parser = (TakeWhile1(char::is_alphabetic), Optional('!'))
        .map(|(word, exclamation)| {
            Value {
                word: word,
                exclamation: exclamation.is_some(),
            }
        });

    println!("{:?}", parser.parse("foo", 0));
    println!("{:?}", parser.parse("foo!", 0));
    println!("{:?}", parser.parse("!", 0));
}
```

Output:

```
Ok((3, Value { word: "foo", exclamation: false }))
Ok((4, Value { word: "foo", exclamation: true }))
Err((0, TakeWhile1))
```

Let me know if you decide to use munch. I'd be happy to help in any way I can! I originally released munch because I wanted to create a templating language for Rust but I haven't been able to start on that yet.

**Comment by donaldpipowitch** [comment]
Cool, thank you very much for your response and the examples. Thank you. I'll write again when I have more questions.
